### ISSUE TITLE
error on windows setup

### ISSUE THREAD

**Issue by sohum26** [pg07codes/gitn#2]
![err](https://user-images.githubusercontent.com/44091750/86276011-c8e22e00-bbf1-11ea-99a7-49de46145178.PNG)

**Comment by pg07codes** [comment]
For the first issue - i will resolve it asap.

Second one is probably due to very old node version. Please update your node version to  `>10` for `gitn` to work correctly.

**Comment by sohum26** [comment]
solved now. thanks.
